---
- name: installeren van lib
  hosts: RPI
  tasks:
   - name: spel kopieren
     copy:
      src: /home/andres/Desktop/workspace/Devops-project-rpi
      dest: /home/pi/Desktop/

   - name: dockerfile kopieren
     copy:
      src: /home/andres/Desktop/workspace/Devops-project-rpi/Dockerfile
      dest: /home/pi/Desktop/

   - name: image aanmaken
     shell: |
      cd /home/pi/Desktop/
      docker build -t dockerimage .
