---
- name: installeren van lib
  hosts: RPI

  tasks:
   - name: spel kopieren
     copy:
      src: /home/andres/Desktop/workspace/Devops-project-rpi
      dest: /home/pi/Desktop/

   - name: dockerfile kopieren
     copy:
      src: /home/andres/Desktop/Dockerfile
      dest: /home/pi/Desktop/

   - name: image aanmaken
     #docker_image:
       #path: /home/andres/Desktop
       #name: devopsproject
     shell: |
      cd /home/pi/Desktop/
      docker build -t dockerimage .
